"""initial_schema

Revision ID: 06db06ce923a
Revises: 
Create Date: 2023-02-27 00:18:48.198587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06db06ce923a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level1_treasure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('num_invicta_collected', sa.Integer(), nullable=True),
    sa.Column('num_dynari_collected', sa.Integer(), nullable=True),
    sa.Column('num_ephilia_collected', sa.Integer(), nullable=True),
    sa.Column('num_akrona_collected', sa.Integer(), nullable=True),
    sa.Column('num_solaris_collected', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.Text(), nullable=True),
    sa.Column('num_kills', sa.Integer(), nullable=False),
    sa.Column('num_level1_treasures_wanderer', sa.Integer(), nullable=False),
    sa.Column('num_level2_treasures_wanderer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level2_treasure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('treasure_type', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('collected_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collected_by_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_treasure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level1_treasure_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level1_treasure_id'], ['level1_treasure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_treasure')
    op.drop_table('level2_treasure')
    op.drop_table('player')
    op.drop_table('level1_treasure')
    op.drop_table('game_status')
    # ### end Alembic commands ###
