"""Added Treasure Counts inside Player as a fallback option

Revision ID: 61e66fd649f8
Revises: dcead36a75e9
Create Date: 2022-07-30 09:15:49.614551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e66fd649f8'
down_revision = 'dcead36a75e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('num_level1_treasures_wanderer', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('num_level2_treasures_wanderer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'num_level2_treasures_wanderer')
    op.drop_column('player', 'num_level1_treasures_wanderer')
    # ### end Alembic commands ###
