"""Added Failed Level1Treasure and Kills Counter as fallback score collector

Revision ID: 6c4af87bb334
Revises: 54ca808367fb
Create Date: 2022-08-03 21:05:06.921955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4af87bb334'
down_revision = '54ca808367fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('num_temp_failed_treasure1_feedback', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('num_temp_failed_kills', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'num_temp_failed_kills')
    op.drop_column('player', 'num_temp_failed_treasure1_feedback')
    # ### end Alembic commands ###
