"""Changed Level1Treasure Many-to-Many Table Structure

Revision ID: dcead36a75e9
Revises: 0af3d19f7eb5
Create Date: 2022-07-29 18:18:06.702110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcead36a75e9'
down_revision = '0af3d19f7eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_treasure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level1_treasure_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level1_treasure_id'], ['level1_treasure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.alter_column('level1_treasure', 'id', type_=sa.INTEGER, nullable=False, autoincrement=True,
                    existing_autoincrement=True)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_treasure')
    # ### end Alembic commands ###
